  // Declared an array of items
  export const RecipeOneTimestamps = [
    "00:00 - We are live!",
    "00:47 - Tom unveils favorite kitchen gadget",
    "02:43 - Preparing today's beverages",
    "04:00 - Starting the birria sauce",
    "07:00 - Spike walking through the birria sauce",
    "10:50 - Tom Seasoning the short ribsw ",
    "19:53 -  Spike experiences capsiscin to the face",
    "21:36 Spike's Short Rib tips",
    "23:40 Tom's take on recipes ",
    "25:00 Tom prepares and cooks duck ",
    "25:56: Tom Charring Red Onions",
    "27:34 - How Tom came up with the idea for duck tacos.",
    "30:59- Corn or Flour tortillas?",
    "32:36- Duck Breast Sear Close up",
    "33:10- SPIKE'S MID-STREAM RECAP",
    "34:08 Tom's charred onions, scallions and sauce",
    "34:25 - Duck Cooking Tips Recap",
    "35:00 - Birria Recap",
    "35:50 - Saucing garlic in duck fat",
    "37:02- Short Rib Braising and Duck simmering Spike Cam",
    "37:45 - Short Rib Insta-pot settings",
    "39:36 - Tom's herb salad update",
    "42:38 - Preparing the quesatacos",
    "44:43- Searing questacaos",
    "46:45 - Tom's duck taco assembly and taste test",
    "48:55 - Tom's duck taco herb salad recap and tips"
  ];