  export const RecipeOneIngredients = [
    "5 Dried Guajilo Chiles",
    "3 Dried Morita Chiles",
    "3 Dried Pasilla Chiles",
    "1 1/2 Tbsp. Vegetable Oil",
    "4 LB. Short Ribs, Or Beef Shank",
    "Kosher Salt",
    "Freshly Ground Black Pepper",
    "8 Garlic Cloves",
    "12 Whole Cloves",
    "1 Cinnamon Stick",
    "1 TSP. Dried Oregano",
    "1 1/2 TSP. Cumin Seeds",
    "3 Roma Tomatoes, Halved",
    "1/4 C. White Wine Vinegar",
    "1 Large Onion, Quartered",
    "5 Bay Leaves",
    "4 Oz Mexican Chocolate",
    "Corn tortillas",
    "Shredded Oaxaca or mozzarella cheese",
    "Freshly chopped cilantro for topping",
    "1 large white onion, finely chopped for topping",
    "Lime wedges for topping"
  ];